sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

script:
    - my_name=start-points-custom
    - my_url=https://github.com/cyber-dojo/${my_name}.git
    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo
    - sudo ./cyber-dojo start-point create custom --git=${my_url}
    - sudo ./cyber-dojo start-point ls
    - sudo ./cyber-dojo start-point ls | grep custom